# -*- coding: utf-8 -*-
"""Train Yolo_v4 Object Detection

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16vm9cldrrptoGd_jvYsAh1rT20B8lTMw
"""

#Mount the google drive
from google.colab import drive
drive.mount('/content/drive')

# Importing necessary libraries
import os

#Create Symbolic Link
!ln -s '/content/drive/My Drive/' /currdrive

# Set Image Directory path
path = '/content/drive/My Drive/YOLO_V4'
os.chdir(path)

# Clone Darknet Repo
!git clone https://github.com/AlexeyAB/darknet

# Verify CUDA version
!/usr/local/cuda/bin/nvcc --version

#Google Colab uses following CUDA, cuDNN and OpenCV version

# CUDA-version: 10010 (10010), cuDNN: 7.6.5, GPU count: 1  
# OpenCV version: 3.2.0

# Compile Darknet Framework in order to use related files for training Object Detection Model
os.chdir('/content/drive/My Drive/YOLO_V4/darknet')
!make

# Verify Installation
!./darknet

# Download YOLO_v4 weights
!wget https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v3_optimal/yolov4.weights

# Run object detection on test image referred as myimage.jpg
!./darknet detector test cfg/coco.data cfg/yolov4.cfg yolov4.weights data/Nikhil.jpg

# Run below lines of code if in case you get Permission Denied Error
# !sudo chmod +x darknet
# !./darknet

# Commented out IPython magic to ensure Python compatibility.
import cv2
import matplotlib.pyplot as plt
# %matplotlib inline

image = cv2.imread('predictions.jpg')
fig = plt.gcf()
fig.set_size_inches(12, 14)
plt.imshow(image)

!./darknet detector demo cfg/coco.data cfg/yolov4.cfg yolov4.weights -dont_show data/VID.mp4 -i 0 -out_filename obj_det_video.avi

# Download the video showing object detection on local system
from google.colab import files
files.download('obj_det_video.avi')

!./darknet detector demo cfg/coco.data cfg/yolov4.cfg yolov4.weights -dont_show data/VID.mp4 -i 0 -out_filename obj_det_video.avi

"""Train Glove and Helmet Object Detection model."""

# Download YOLO_v4 conv 137 pretrained weight for Convoluntional layers
!wget https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v3_optimal/yolov4.conv.137

#change directory and provide permission to the darknet folder 
os.chdir('/currdrive/YOLO_V4/darknet')
!sudo chmod +x darknet
!./darknet

#Train the Glove and Helmet Object Detection Model
!./darknet detector train data/Glove_Helmet/image_data.data cfg/yolov4_train.cfg yolov4.conv.137 -dont_show

#Starting the model form last weights
!./darknet detector train data/Glove_Helmet/image_data.data cfg/yolov4_train.cfg /currdrive/YOLO_V4/darknet/backup/yolov4_train_last.weights -dont_show

#Starting the model form last weights
!./darknet detector train data/Glove_Helmet/image_data.data cfg/yolov4_train.cfg /currdrive/YOLO_V4/darknet/backup/yolov4_train_last.weights -dont_show

#Starting the model form last weights
!./darknet detector train data/Glove_Helmet/image_data.data cfg/yolov4_train.cfg /currdrive/YOLO_V4/darknet/backup/yolov4_train_last.weights -dont_show

#Starting the model form last weights
!./darknet detector train data/Glove_Helmet/image_data.data cfg/yolov4_train.cfg /currdrive/YOLO_V4/darknet/backup/yolov4_train_last.weights -dont_show



# Run below lines of code if in case you get Permission Denied Error
!sudo chmod +x darknet
!./darknet

# Commented out IPython magic to ensure Python compatibility.
import cv2
import matplotlib.pyplot as plt
# %matplotlib inline

#Loading the image for testing
!./darknet detector test data/Glove_Helmet/image_data.data cfg/yolov4_train.cfg /currdrive/YOLO_V4/darknet/backup/yolov4_train_last.weights /currdrive/YOLO_V4/darknet/data/test_data/Worker.jpg -thresh 0.3

image = cv2.imread('predictions.jpg')
fig = plt.gcf()
fig.set_size_inches(12, 14)
plt.imshow(image)

# Run below lines of code if in case you get Permission Denied Error
!sudo chmod +x darknet
!./darknet

!./darknet detector demo data/Glove_Helmet/image_data.data cfg/yolov4_train.cfg /currdrive/YOLO_V4/darknet/backup/yolov4_train_last.weights /currdrive/YOLO_V4/darknet/data/test_data/Workers_dance.mp4 -out_filename result.avi -ext_output -dont_show

!./darknet detector demo data/Glove_Helmet/image_data.data cfg/yolov4_train.cfg /currdrive/YOLO_V4/darknet/backup/yolov4_train_last.weights /currdrive/YOLO_V4/darknet/data/test_data/Workers_dance1.mp4 -out_filename result1.avi -ext_output -dont_show

!./darknet detector demo data/Glove_Helmet/image_data.data cfg/yolov4_train.cfg /currdrive/YOLO_V4/darknet/backup/yolov4_train_last.weights /currdrive/YOLO_V4/darknet/data/test_data/Workers_dance2.mp4 -out_filename result3.mp4 -ext_output -dont_show

